apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: knginx-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: knginx
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 3
