apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: harbor
  annotations:
    traefik.frontend.rule.type: PathPrefix  
spec:
  rules:
  - host: registry.spacecig.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 80
      - path: /v2
        backend:
          serviceName: registry
          servicePort: 5000        
      - path: /service
        backend:
          serviceName: ui
          servicePort: 80              
  - host: docker.ispacesys.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 80
      - path: /v2
        backend:
          serviceName: registry
          servicePort: 5000        
      - path: /service
        backend:
          serviceName: ui
          servicePort: 80    
