apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  UI_SECRET: "BBRQwySksiHZqJUh"
  JOBSERVICE_SECRET: "HM9jKtcl9FZUGMtT"
  SECRET_KEY: "nQImBn5SVCHL7ehq"
  MAX_JOB_WORKERS: "3"
  LOG_LEVEL: warn
  GODEBUG: netdns=cgo
  CONFIG_PATH: /etc/jobservice/app.conf
  ADMIN_SERVER_URL: http://adminserver
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
