apiVersion: v1
kind: ReplicationController
metadata:
  name: jobservice-rc
  labels:
    name: jobservice-rc
spec:
  replicas: 1
  selector:
    name: jobservice-apps
  template:
    metadata:
      labels:
        name: jobservice-apps
    spec:
      nodeSelector:
        kubernetes.io/hostname: 192.168.74.102
      containers:
      - name: jobservice-app
        image: reg.local:5000/public/harbor-jobservice:v1.2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: ADMIN_SERVER_URL
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: ADMIN_SERVER_URL        
          - name: UI_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: JOBSERVICE_SECRET
          - name: CONFIG_PATH
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: CONFIG_PATH
          - name: LOG_LEVEL
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: LOG_LEVEL
          - name: GODEBUG
            valueFrom: 
              configMapKeyRef: 
               name: harbor-jobservice-config
               key: GODEBUG
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/jobservice
        - name: logs
          mountPath: /var/log/jobs
      volumes:
      - name: config
        configMap:
          name: harbor-jobservice-config
          items:
          - key: config
            path: app.conf
          - key: SECRET_KEY
            path: key  
      - name: logs
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: harbor-log
            clusterNamespace: kube-public 
#        persistentVolumeClaim:
#          claimName: log-pvc 
        
