apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: http
      port: 80
  selector:
    name: nginx-apps
#  Set the external IP to an IP of the cluster node, so that the service can be accessed from outside the kubernetes cluster.
#  externalIPs:
#  - 10.192.168.5
