apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc-cephfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: storage
