apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv-cephfs
  labels:
    type: storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/harbor/storagenew
